### ISSUE TITLE
Update `dependabot` to use `flutter pub get` properly

### ISSUE THREAD

**Issue by literalEval** [PalisadoesFoundation/talawa#1643] opened 2023-03-09 05:50 UTC
**Describe the bug**
After our migration to Flutter 3.7.3, the new `pub get` command adds `sha256` hash of each plugin to `pubspec.lock`. The problem is that `dependabot` somehow does not generate these hashes (this might mean that it is using an old version of flutter sdk ?), changing `pubspec.lock` entirely.

This has some issues as 
1. Contributors will have conflicts with `pubspec.lock` as their version of the file has `sha256` hashes while the `dependabot` version has not.
2. Next PR will need to fix `pubspec.lock` again, which is not good because they will need to work with files they are not supposed to work with. 
3. If the next PR doesn't fix `pubspec.lock`, then that's again an issue because then the `flutter pub get` in our workflow (which uses latest version of flutter) will complain about `pubspec.lock` being not in the format it expects.

**To fix**

Find out the internals of `dependabot` and which version of `Dart SDK` it uses and upgrade it to use the latest version.

**Important Links**

- The [pub beta support for Dependabot version updates](https://github.blog/changelog/2022-04-05-pub-beta-support-for-dependabot-version-updates/) blog post
- The Talawa repository's [dependabot.yaml](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/dependabot.yaml) file

**Comment by xoldyckk** [comment] 2023-03-13 13:38
@literalEval Btw if dependabot is too much of a problem, there's an alternative too, it's called renovate. It's has much more features I've heard. But dependabot integrated into github so using it is easy.

**Comment by literalEval** [comment] 2023-03-13 13:46
@xoldyckk yeah that is the point. Dependabot comes prebuilt so our initial idea is to work it out. If it can not be made to work anyhow, then maybe we will think of other solutions.

**Comment by xoldyckk** [comment] 2023-03-13 14:12
> @xoldyckk I discussed with @palisadoes to remove dependabot and use some alternative. But he insisted on making dependabot work somehow. Maybe he had something in mind.

Probably the ease of integration with github.

**Comment by palisadoes** [comment] 2023-03-13 18:05
1. This issue was created to see whether we could get dependabot to work as it is the GitHub default.
2. We need a solution to keep the repository dependencies up to date. 
3. If dependabot cannot work, we can certainly find something else.

**Comment by literalEval** [comment] 2023-03-13 18:25
Point 3 is great. Sure we can look into renovate.

**Comment by SiddheshKukade** [comment] 2023-03-16 03:16
@palisadoes Sir, I'd like to get assigned to this issue.

**Comment by xoldyckk** [comment] 2023-03-16 04:44
@literalEval Just wanted to let you know that the configuration for dependabot.yml for this repo was set up by me. I followed the official docs on it, but more atomic improvements could be made to the configuration according to your requirements. I just followed the most generic guide, because I'm not at all familiar with dart and flutter.

**Comment by SiddheshKukade** [comment] 2023-03-19 11:11
@xoldyckk Dependabot was not working even after enforcing the flutter version.
I've also tried to get feedback about this from the community and have posted a [question on StackOverflow about dependabot](https://stackoverflow.com/questions/75751974/dependabot-version-fails-due-to-outdated-flutter-version).
But I haven't received any answers on that.
I got a reply from a person here https://github.com/dev-yakuza/dev-yakuza.github.io/issues/79#issuecomment-1475200148 who said that:
> The Dart package manager uses https://pub.dev by default. However, GitHub Dependabot uses https://pub.dartlang.org by default.

> So, I think there is no way to fit it, currently. If I find the solution, I will share it.

I tried `renovate bot` on one of my old flutter repository  https://github.com/SiddheshKukade/sample-flutter/ to test it.
Seems like it only changes the `yaml` file and not the lock file. 
Is this an expected behaviour according to you ? 

![image](https://user-images.githubusercontent.com/65951872/226171361-baea2622-1af0-4e9c-a451-ff28200dc252.png)

I think we can implement this for now until the dependabot issues is fixed. As it only updates the `pubspec.yaml` file  then `pubspec.lock` file might be update in the future PRs by any contributors by simply doing `flutter pub get`.

**Comment by literalEval** [comment] 2023-03-19 11:19
@SiddheshKukade this is not a complete solution as the lock file must be updated with each update in pubpsec.yaml.
Also, if we want to depend on the future PRs by contributors, then that's already happening anyway.

**Comment by SiddheshKukade** [comment] 2023-03-19 11:40
Yes, it's not but currently the `dependabot` is also not working properly.
As [stated here ](https://github.com/dependabot/dependabot-core/tree/main/pub#detection-of-flutter-and-dart-sdk-versions) It should work on the stable channel 

And also from the code of dependabot repo it should check the versions from  the `environment` property of the yaml file. But it's not and giving the wrong implementation in PRs:[ (you can check here) ](https://github.com/SiddheshKukade/talawa/pulls) 
https://github.com/dependabot/dependabot-core/blob/c72a2b6d06c653e19ce1c9ca29b9a32265024b3f/pub/helpers/bin/infer_sdk_versions.dart#L48-L58
![image](https://user-images.githubusercontent.com/65951872/226172709-d54dc8aa-6b9b-460f-b7ad-6c3258ca7073.png)

**Comment by literalEval** [comment] 2023-03-19 11:51
I think we should go with Renovate.

**Comment by xoldyckk** [comment] 2023-03-19 13:24
I don't have any knowledge about these automatic dependency managers, most of the times they'd work without needing much manual configuration. Mostly it needs to abide by the lock file so that it doesn't accidently update something which can break the system(though that depends on whether the packages used in the project themselves are following semantic versioning and stuff). I can't answer technical questions related to pub package manager and it's lock file and how dependabot works with it. I've never used dart/flutter.

Though I've read the dart/flutter dependency management was recently made available with dependabot. So, there are bound to be problems with it I guess cuz it's just released a few months back.

But yeah I've heard great things about renovate and most big organizations and projects on github I've seen use renovate instead of dependabot for this stuff.

**Comment by palisadoes** [comment] 2023-03-19 13:39
@SiddheshKukade We need a workable solution and the GitHub default isn't it. Please investigate the alternative.

**Comment by SiddheshKukade** [comment] 2023-03-19 18:48
> Though I've read the dart/flutter dependency management was recently made available with dependabot. So, there are 
> bound to be problems with it I guess cuz it was just released a few months back.

@xoldyckk  I was also thinking the same. 👍🏻 

---

>I don't want the mobile app to fall behind in updates

@palisadoes, Sure I'll let you know.

**Comment by SiddheshKukade** [comment] 2023-03-19 18:48
> Though I've read the dart/flutter dependency management was recently made available with dependabot. So, there are 
> bound to be problems with it I guess cuz it was just released a few months back.

@xoldyckk  I was also thinking the same. 👍🏻 

---

>I don't want the mobile app to fall behind in updates

@palisadoes, Sure I'll let you know.

**Comment by SiddheshKukade** [comment] 2023-03-25 05:45
Some updates from the [dependabot/dependabot-core ](https://github.com/dependabot/dependabot-core)maintainers.

1. They've added [my issue ](https://github.com/dependabot/dependabot-core/issues/6867) as a `bug` 
2. They suggested some workaround to try to check if it works but it wasn't working in dependabot.
3. According to them merging the below PR in dependabot will resolve this issue (by upgrading the dart version of dependabot) 
    -  https://github.com/dependabot/dependabot-core/pull/6454
4. They've also said a [PR is recently added in `dartlang` repo](https://github.com/dart-lang/pub/commit/29a7c0990cf070aa118570554f89402c37b54cf6) for adding support for `sha` hash. Here's the code that does that https://github.com/dart-lang/pub/blob/29a7c0990cf070aa118570554f89402c37b54cf6/lib/src/command/dependency_services.dart#L550-L566

I think we should now wait to see @depedabot's further PRs in talawa to see if the issue got fixed or not.

**Comment by literalEval** [comment] 2023-03-25 05:48
Sounds good to me.

**Comment by palisadoes** [comment] 2023-03-25 05:54
Will this be backward compatible with older versions of Dart? For example, the user could have the option of specifying the preferred version in YAML. A possibly better approach would be to auto detect the version of code.

**Comment by literalEval** [comment] 2023-03-25 05:56
@palisadoes everyone has the latest migrated version of Talawa codebase, so backward compatibility should not be a problem. Am I correct @SiddheshKukade ?

**Comment by SiddheshKukade** [comment] 2023-03-25 05:56
> Will this be backwards compatible with older versions of Dart? For example, the user could have the option of specifying the preferred version in YAML. A possibly better approach would be to auto detect the version of code.
>
Yes they've added backward compatibility in here with an `if` condition:
https://github.com/dart-lang/pub/blob/29a7c0990cf070aa118570554f89402c37b54cf6/lib/src/command/dependency_services.dart#L550-L566
> Is my question relevant in this context?

Yes

**Comment by SiddheshKukade** [comment] 2023-03-25 05:57
> @palisadoes everyone has the latest migrated version of Talawa codebase, so backward compatibility should not be a problem. Am I correct @SiddheshKukade ?

@literalEval Yes, In the context of talawa app everyone uses the common version. Otherwise it won't work.

**Comment by SiddheshKukade** [comment] 2023-03-25 06:11
@palisadoes Sir, can I work on other issues in the meantime until https://github.com/dependabot/dependabot-core/pull/6454 gets merged?

**Comment by palisadoes** [comment] 2023-03-25 06:42
Will this be backward compatible with older versions of Dart? For example, the user could have the option of specifying the preferred version in YAML. A possibly better approach would be to auto detect the version of code.



OK

**Comment by palisadoes** [comment] 2023-03-25 06:46
> @palisadoes Sir, can I work on other issues in the meantime until https://github.com/dependabot/dependabot-core/pull/6454 gets merged?

OK

**Comment by literalEval** [comment] 2023-05-13 01:45
@SiddheshKukade what is the progress on this ? Why do we still need to manually bump package versions ?

**Comment by SiddheshKukade** [comment] 2023-05-13 01:47
@literalEval the PR that fixes this is still not merged from Jan on the main dependabot repo.

**Comment by literalEval** [comment] 2023-05-13 01:50
Hmm. That's sad. Can we do anything to get it merged ?

**Comment by palisadoes** [comment] 2023-05-14 02:53
https://github.com/dependabot/dependabot-core/issues/6929#issuecomment-1546733884 

They merged this. It looks like it's fixed and just waiting to be pushed to the GitHub workflow

**Comment by palisadoes** [comment] 2023-05-15 13:34
https://github.com/dependabot/dependabot-core/issues/6929#issuecomment-1547852003

It's live. We can close this.

**Closed** 2023-05-15 13:34 UTC
Labels: bug, no-issue-activity
