### ISSUE TITLE
exceeding the limit of integer in idToColor function in file members.dart

### ISSUE THREAD

**Issue by GMGOG** [PalisadoesFoundation/talawa#236] opened 2021-03-14 10:22 UTC
This one is breaking the custom sliver list view UI.
![SS of member screen](https://user-images.githubusercontent.com/43651504/111064859-77a67000-84dc-11eb-9735-6cbd6fe39634.jpeg)

Can I raise PR for the following issue? @Sagar2366 

PS: I fixed this issue
 
![ss fixed](https://user-images.githubusercontent.com/43651504/111064967-34003600-84dd-11eb-9b9a-743d8926d59a.jpeg)

**Comment by yasharth291** [comment] 2021-03-14 10:26
this issue is already present  #199  please read that. And i think other person is working on it. Please once read the previous issues #199

**Comment by Sagar2366** [comment] 2021-03-14 10:28
@GMGOG , you are more than welcome to contribute to project. Please check existing issues and make sure you are creating duplicate issues.

**Comment by GMGOG** [comment] 2021-03-14 10:29
oh But I already fixed it so I thought to raise a PR as if he hasn't completed the fix.

**Comment by Sagar2366** [comment] 2021-03-14 12:52
Closing this issue as it is duplicate of https://github.com/PalisadoesFoundation/talawa/issues/199 and fixed as part of https://github.com/PalisadoesFoundation/talawa/pull/229

**Closed by Sagar2366** 2021-03-14 12:52 UTC
