### ISSUE TITLE
Views: Create tests for map_screen.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#1403] opened 2023-01-24 03:14 UTC
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `lib/views/after_auth_screens/venue/map_screen.dart`

- When complete, all methods, classes and/or functions in the file will need to be tested. 
- These tests must be placed in a single file with the name `test/views/after_auth_screens/venue/map_screen_test.dart`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- https://github.com/PalisadoesFoundation/talawa/issues/1217

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa/tree/develop/lib/views/after_auth_screens/venue/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide.
- You can verify your own code coverage by creating an account at [Codecov.io](https://codecov.io)
- No functionality must be removed to achieve this goal.

**Comment by Adiii1436** [comment] 2023-02-05 19:45
Hello @palisadoes ! I want to work on this issue . Please assign this issue to me.

**Comment by literalEval** [comment] 2023-02-16 13:00
@palisadoes please assign this to me.

**Comment by palisadoes** [comment] 2023-02-16 13:20
@literalEval are already working on other issues

**Comment by Skdahale** [comment] 2023-02-18 11:26
@palisadoes Can I work on this issue?

**Comment by noman2002** [comment] 2023-02-18 17:29
Sure. Go ahead. @Skdahale

**Comment by palisadoes** [comment] 2023-03-05 23:24
@Skdahale I'm going to unassign due to inactivity. It's been 2 weeks, we need to give others a chance.

**Comment by Manik2708** [comment] 2023-12-17 10:04
Duplicate of #2146, please close this issue.

**Comment by Cioppolo14** [comment] 2023-12-29 01:24
Closing as a duplicate.

**Closed by Cioppolo14** 2023-12-29 01:24 UTC
Labels: good first issue, test, points 01
