### ISSUE TITLE
Bug Report: Error in lines 105 and 125 of the file lib/view_models/main_screen_view_model

### ISSUE THREAD

**Issue by antonio-pedro99** [PalisadoesFoundation/talawa#1431] opened 2023-01-27 06:07 UTC
**Describe the bug**
I recently got an issue assigned to me and I was trying to setup my local env. The file main_screen_view_model on lib/view_models has errors in lines 105 and 125 respectively. The problem is related to wrong parameters of the class TutorialCoachMark.
vs code error message: 
`BuildContext context
Type: BuildContext

package:talawa/view_model/main_screen_view_model.dart

Too many positional arguments: 0 expected, but 1 found.
Try removing the extra positional arguments, or specifying the name for named arguments.dart[extra_positional_arguments_could_be_named](https://dart.dev/diagnostics/extra_positional_arguments_could_be_named)`
**To Reproduce**

1. open the project
2. got to lib/view_models/main_screen_view_model

**Expected behavior**
There should not be erros in these lines.

**Actual behavior**
There are red lines in this file.

**Screenshots**
![Screenshot from 2023-01-27 11-36-38](https://user-images.githubusercontent.com/42675180/215020610-d92d84ea-5d0b-41d6-9ed7-128befc9a9be.png)

**Additional details**
I have already solved the issue. Please assign it to me so that I can make a pull request.

**Comment by noman2002** [comment] 2023-01-27 07:09
@antonio-pedro99 I can't reproduce this error. Have you pulled the recent changes ??

**Comment by antonio-pedro99** [comment] 2023-01-27 07:17
@noman2002  not yet. I have not pulled!
Once I cloned the repo(on develop branch), I ran `flutter pub get` 
everything except this file and setup_firebase_mocks are working fine.

**Comment by noman2002** [comment] 2023-01-27 07:22
There might be some issue with your setup. Please try to communicate in the slack channel to get this resolved. I am closing this issue.

**Closed by noman2002** 2023-01-27 07:22 UTC
Labels: bug, unapproved

**Comment by antonio-pedro99** [comment] 2023-01-28 09:21
@noman2002 as I just forked the repository, I don't think I have to pull it again. 
Here is my flutter env:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on Ubuntu 20.04.5 LTS 5.15.0-58-generic,
    locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.74.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
