### ISSUE TITLE
[Bug] Register for event doesn't work

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#188] opened 2021-03-14 04:18 UTC
when clicked on register for event the screen only loads. And stucks at a place.

**Comment by yasharth291** [comment] 2021-03-14 04:39
@Sagar2366

**Comment by pr4nshul** [comment] 2021-03-25 09:30
Hey @yasharth291 are you working on it? If not @Sagar2366 can you assign me this. Also, adding an event is also not working at least on my end. So should I create a new issue for the same?

**Comment by Sagar2366** [comment] 2021-03-25 09:36
@pr4nshul you can start working on this issue.
About add event there is open issue   https://github.com/PalisadoesFoundation/talawa/issues/426 @CoderMayhem working on it.

**Comment by pr4nshul** [comment] 2021-03-25 09:37
Ok, got it

**Comment by pr4nshul** [comment] 2021-03-25 09:42
I was thinking we should also add a button to unregister in the drop down.

**Comment by pr4nshul** [comment] 2021-03-25 20:20
@Sagar2366 Close this issue as you mentioned it is solved in previous master changes.
 But I still think , that small UI improvement will be helpful for user :)

**Comment by Sagar2366** [comment] 2021-03-26 02:45
> @Sagar2366 Close this issue as you mentioned it is solved in previous master changes.
> But I still think , that small UI improvement will be helpful for user :)

@pr4nshul be clear when you say small UI improvement. If you are talking about registering for the event it is already done and don't need any UI change. But if you are referring to unregister option then please continue discussion on slack. We welcome new ideas from students and hear everyone's opinions. At the same time we expect everyone to follow the guidelines - discuss idea first in slack channels and based on discussion create new issue.

Avoid suggesting new ideas/new issue discussions here in another issue. As explained you earlier if makes difficult to keep track of ongoing issue.

**Comment by pr4nshul** [comment] 2021-03-26 05:49
Ok so what i mean bt small UI improvement is , when the user clicks the register button the screen doesn't refresh instantly and it displays you are not registered until you refresh . I will send a video for the same in few minutes. And with the changes that I made that on the PR the page get reloaded as soon as the user registers for the event. Hence , user doesn't need to refresh manually to see whether he was able to register for the event or not. 
I was not talking about the unregister button.

**Comment by pr4nshul** [comment] 2021-03-26 06:08
https://user-images.githubusercontent.com/51524156/112589705-93d4d600-8e27-11eb-8b52-be33bd31422a.mp4
This is on current master

https://user-images.githubusercontent.com/51524156/112589741-a222f200-8e27-11eb-9f31-95f5e647f75f.mp4
This is after the changes I have in PR #509

**Comment by pr4nshul** [comment] 2021-03-26 06:08
https://user-images.githubusercontent.com/51524156/112589851-d39bbd80-8e27-11eb-9d83-3949e5b813ba.mp4


This is after the changes I have in PR #509

**Comment by pr4nshul** [comment] 2021-03-27 19:05
Hey @Sagar2366 , did you look at this? If you think this change is redundant then I would close this issue.

**Comment by yasharth291** [comment] 2021-04-03 16:12
Is it solved @pr4nshul  @Sagar2366  sir

**Comment by pr4nshul** [comment] 2021-04-03 16:14
The button is working as intended, we just need proper state management to update the user that they are registered . So, you can close the issue, I guess.

**Comment by yasharth291** [comment] 2021-04-03 16:29
@Sagar2366 sir can you please close it

**Closed** 2021-04-04 14:48 UTC
Labels: bug
