### ISSUE TITLE
[Enhancement] - Adding Support for Internationalization

### ISSUE THREAD

**Issue by adithyaakrishna** [PalisadoesFoundation/talawa#576] opened 2021-03-31 09:11 UTC
**Description:** As Talawa App would be released world wide, we would need the app to support across multiple languages to cater different users and their language preferences.

**Problem:** The existing App has support only for English and these words are coded in the app itself, what would be good is, if we can use localized words using .arb files to support for custom texts and other parts, we would have a greater app with wide language support also. 

**Are You Willing to Work On This:** Yes

**Comment by lakshydeep-14** [comment] 2021-03-31 14:24
I wana work on this. I can solve this issue.

**Comment by sumitra19jha** [comment] 2021-04-01 14:26
hey this is duplicate of #555

**Comment by arteevraina** [comment] 2021-04-03 02:53
Hey @adithyaakrishna @lakshydeep-14! Thanks for opening this issue. But, this itself is one of the features that need to be developed in GSoC 21. https://palisadoesfoundation.github.io/talawa-docs/docs/gsoc/gsoc-ideas

**Closed** 2021-04-04 13:17 UTC
Labels: duplicate, hold, unapproved
