### ISSUE TITLE
[Bug] - New User signup home screen issue after successful login.

### ISSUE THREAD

**Issue by CyberWake** [PalisadoesFoundation/talawa#288] opened 2021-03-14 18:37 UTC
Description:
When a new user signs up to the app successfully and then joins any of the organization he is navigated to a page which is almost a dead end i.e it does not show the bottom navigation bar it just displays the profile page disabling the user to navigate to posts page, messages page, events page and members page.

Expected:
On successful signup and joining any organization or creating any new organization the user should see the home page not just the profile page so that the app doesn't become void on first time signup.
https://drive.google.com/file/d/1_Bc3ZrWARZtT6G80ia8LOYdCOfSrN3tN/view?usp=sharing

Observed:
On successful signup and joining any organization or creating any new organization user lands to the profile page which doesn't have bottom navigation bar and hence he is not able to navigate to any other activities of the joined organization.
https://drive.google.com/file/d/1tesfVODfcvVwXJF8nmt8gtFOwVog_sVJ/view?usp=sharing

Solution:
Need to navigate the user not to profile page rather navigating the user to homepage after the respective flow.

**Comment by CyberWake** [comment] 2021-03-14 18:37
Please assign this to me:relaxed:

**Comment by yasharth291** [comment] 2021-03-14 18:46
this is duplicate issue can you please read the issues made before this one

**Comment by CyberWake** [comment] 2021-03-14 18:47
Can you mark the previous issue. I didn't find the one.

**Comment by yasharth291** [comment] 2021-03-14 18:54
#193

**Comment by Sagar2366** [comment] 2021-03-15 19:00
Marking this as duplicate of https://github.com/PalisadoesFoundation/talawa/issues/184

**Closed by Sagar2366** 2021-03-15 19:00 UTC
Labels: duplicate
