### ISSUE TITLE
App not starting when release apk is run

### ISSUE THREAD

**Issue by Hrishikesh-Bhagwat** [PalisadoesFoundation/talawa#524] opened 2021-03-26 10:54 UTC
Issue Description:
If we build the release apk and install on mobile, there is only a white screen at the start. The UI does not load.

Observed Behaviour:
A plain white screen loads, the ui does not load. 

Expected Behaviour:
The url page should have loaded.

Snapshot:
https://drive.google.com/file/d/1EKvF46wgp4Ikaa_JNqpgZk5OHGcYDZ2q/view?usp=sharing

Does this issue need immediate attention?
Yes

Are you willing to work on this issue:
Yes

**Comment by Hrishikesh-Bhagwat** [comment] 2021-03-26 14:46
I was able to fix this issue by not shrinking the resources. This was caused due to the shared preferences plugin.

**Comment by CyberWake** [comment] 2021-03-26 17:23
> I was able to fix this issue by not shrinking the resources. This was caused due to the shared preferences plugin.

Would we happy to help if needed☺️

**Comment by harshkumarkhatri** [comment] 2021-03-27 19:32
I tried reproducing the error on one emulator and one physical device.
It worked fine on my Nexus 5X API 28 emulator but for my physical redmi note 5 device it stuck as mentioned.
Have you tried running the app on any other devices? @Hrishikesh-Bhagwat

**Comment by CyberWake** [comment] 2021-03-27 20:31
The issue is with Android versions oreo and above.

**Comment by Hrishikesh-Bhagwat** [comment] 2021-03-27 21:45
I tried it on multiple devices. Like all the phones I could. But this pr fixes it.

**Comment by CyberWake** [comment] 2021-05-31 23:24
@Hrishikesh-Bhagwat we are migrating the code base and upgrading the dependencies #834 #835 hence we may close this issue as it will be resolved before the code freeze by these issues.

**Closed** 2021-06-01 00:53 UTC
Labels: bug
