### ISSUE TITLE
No update profile page exist 

### ISSUE THREAD

**Issue by shikharsaurav** [PalisadoesFoundation/talawa#398] opened 2021-03-19 07:43 UTC
In profile page when we click on update profile nothing happens

**Comment by shikharsaurav** [comment] 2021-03-19 07:44
plz assign me for adding update profile page

**Comment by Sagar2366** [comment] 2021-03-19 07:54
closing this issue as it is duplicate of https://github.com/PalisadoesFoundation/talawa/issues/174

**Closed by Sagar2366** 2021-03-19 07:54 UTC
Labels: duplicate, unapproved
