### ISSUE TITLE
Custom made Widgets are missing

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#100] opened 2021-03-11 07:18 UTC
![Capture](https://user-images.githubusercontent.com/55004621/110750137-0a8aa480-8268-11eb-8927-76424c6e4e40.JPG)
here custom made Activity is missing

**Comment by jordanliu** [comment] 2021-03-11 14:50
Duplicate of #92

**Closed by jordanliu** 2021-03-11 14:50 UTC
