### ISSUE TITLE
Bug Report    , Help button has no functionality

### ISSUE THREAD

**Issue by sunnyok03** [PalisadoesFoundation/talawa#1107] opened 2022-01-06 18:51 UTC
**Describe the bug**
Nothing happens on clicking the "Help" button in the "Profile" section

**To Reproduce**

1. We can either direct to Gmail or the default mailing app to send the mail to the org on clicking the "Help" button

**Expected behavior**
Should direct to the Gmail

**Actual behavior**
Nothing happens on clicking 

https://user-images.githubusercontent.com/76403273/148434512-67a9ed49-2ccb-4145-95e1-961bb3e0ad73.mp4

**Additional details**
For implementing this I need the org email id to which I can direct this.

PS:- My first issue so there might be some mistake in creating the issue.

**Comment by jaynit1106** [comment] 2022-01-07 17:20
I can help you with issue can you pls assign it to me

**Comment by palisadoes** [comment] 2022-01-07 22:44
- What sort of help are you suggesting to provide?
- How will you ensure the help will work in all language selections?
- If support is being sought, who would be contacted and how would the app know the persons or method to use for contact?

**Comment by jaynit1106** [comment] 2022-01-08 05:45
Basically I was thinking of using the url_launcher package which will lead to the default mailing app of the device.
Basically  mail to your help desk.

**Comment by sunnyok03** [comment] 2022-01-08 07:19
So, actually I myself would like to work on this issue.
Solution:-
On clicking the help button we should direct them to Gmail or their default mailing app and provide our org mail by default so the end-user can mail us their problems and issues.

**Comment by avinashbest** [comment] 2022-02-06 17:50
Hi, I would like to work on this issue.
Solution: 
- We can use the help button to redirect to gmail application. or
- We can add a web-view which opens palisadoes documentation page.
- If any more suggestion you would like I would definitely implement that.

**Comment by palisadoes** [comment] 2022-02-06 17:55
@sunnyok03 The issue is that there is no help documentation to point to, and we do not have a process to respond to emails for assistance. At this point it's best to remove help completely. I've assigned it to you. Please let me know if you are still interested in working on it.

**Comment by sunnyok03** [comment] 2022-02-06 17:59
Yes I can work on this issue plz assign it to me

**Comment by palisadoes** [comment] 2022-02-06 18:11
Done

**Comment by sunnyok03** [comment] 2022-02-07 04:54
I didn't get it assign.

**Comment by palisadoes** [comment] 2022-04-03 01:40
Closing. This is being handled by:

- https://github.com/PalisadoesFoundation/talawa/issues/1183

**Closed by palisadoes** 2022-04-03 01:40 UTC
Labels: bug
