### ISSUE TITLE
[Feature Request] Share News page, display image when selected.

### ISSUE THREAD

**Issue by Omegaviv** [PalisadoesFoundation/talawa#1569] opened 2023-02-26 06:22 UTC
**Is your feature request related to a problem? Please describe.**
After watching the demo video you guys shared (Talawa - Functionality Improvements 2023), in the "Share News" screen while creating the post, there are three icons to upload a photo, the photo is been stored in the File variable but the user has no idea if the image is selected or not.

Current screen after and before image upload/selected
<img src="https://user-images.githubusercontent.com/86337946/221395363-92e12e49-04e2-4838-b84f-d749e7cda4c0.jpg" alt="example image" width="250">

**Describe the solution you'd like**
We can have the image visible on the screen itself after the user has selected the image, with a cross at the top right of the image, which when clicked user has the option to again select an image like before. 

After the user selects an image

<img src="https://user-images.githubusercontent.com/86337946/221395477-f1a91636-b039-4ed8-b677-508048e3b593.png" alt="example image" width="250">

the above design is just to give an idea, let me know if we can make the design more intuitive for the users.

**Approach to be followed (optional)**
simple using the File variable that stores the image we can use if else to change the design.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Omegaviv** [comment] 2023-02-26 06:23
if this sounds good, I would like to work on this, please assign it to me.
if anyone has better ideas or improvements to the above soluting please let me know.

**Comment by palisadoes** [comment] 2023-02-26 12:12
- This is a good start.
- If you can provide a preview that is nearly identical to what it will look like in the feed when posted it'll be even better. Look at other apps that post to news feeds for incorporation.

**Comment by Omegaviv** [comment] 2023-02-26 17:32
but we already have that UI wirtting, right?

<img src="https://user-images.githubusercontent.com/86337946/221426471-6b28dc49-1aab-4c0f-94aa-69eb2ba40062.jpg" alt="example image" width="250">

**Comment by noman2002** [comment] 2023-02-26 19:00
> * This is a good start.
> 
>     * If you can provide a preview that is nearly identical to what it will look like in the feed when posted it'll be even better. Look at other apps that post to news feeds for incorporation.

He meant to say that he wants to add a image preview when an image is uploaded. I thinks its a good idea.

**Comment by palisadoes** [comment] 2023-02-26 20:56
Yes, Noman that's correct.

**Comment by Omegaviv** [comment] 2023-02-28 02:55
okay got it

**Comment by palisadoes** [comment] 2023-03-14 03:41
I'm unassigning you due to inactivity. Please leave a comment here if you want to be reassigned.

**Comment by khaledmurtaja** [comment] 2023-03-14 13:08
Hi @palisadoes  
 I would like to be assigned for the **image preview task**

**Comment by khaledmurtaja** [comment] 2023-03-14 23:34
@palisadoes  
i have followed the installation process for the (mongo DB & node & flutter project& org url), and i got the API running correctly, but i am not able to sign up with the application, App says `select an organisation `but i can not see any thing to select. 
am i missing something
![WhatsApp Image 2023-03-15 at 1 32 53 AM](https://user-images.githubusercontent.com/79102102/225165207-1851a6ba-0536-4d36-a40f-bec8ea052c90.jpeg)

**Comment by khaledmurtaja** [comment] 2023-03-14 23:41
> @palisadoes i have followed the installation process for the (mongo DB & node & flutter project& org url), and i got the API running correctly, but i am not able to sign up with the application, App says `select an organisation `but i can not see any thing to select. am i missing something? ![WhatsApp Image 2023-03-15 at 1 32 53 AM](https://user-images.githubusercontent.com/79102102/225165207-1851a6ba-0536-4d36-a40f-bec8ea052c90.jpeg)

Oh, i figured it out !,  i have forget to install the admin portal for **talawal** which i shoud be using for the creation of an account right?

**Comment by khaledmurtaja** [comment] 2023-03-15 12:32
@palisadoes 
I have unassigned myself by miskake, could you reassign me?

**Comment by palisadoes** [comment] 2023-03-16 18:36
There was a recent PR in the API to fix file uploads. You may want to make sure that the mutation for the feature was updated.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1115

**Comment by khaledmurtaja** [comment] 2023-03-16 18:48
The issue is not related to the Api, its failing on the mobile side before trying to upload it.
I am talking about the process of select an image from gallary, it should be stored correctly  on the RAM so i can retrive it and view it as an **ImagePreview**.

**Comment by khaledmurtaja** [comment] 2023-03-17 21:05
> Update The **getImageFromGallary** function isn't working as expected. It fails to get the image it returns null. So before trying to add the **imagePreviewTask**, i need to figure out why its returning null.

@palisadoes  
as i told you this issue could be divided  into two issues :
**firstly** GetImageFrom gallery does not work properly as a `BugFix`
**secondly** adding an ImagePreview After successfully selecting an image as a `featureRequest` 
may i open a new issue for the first one?

**Comment by palisadoes** [comment] 2023-03-17 21:19
Go ahead

**Comment by RahulYele141** [comment] 2023-03-28 03:04
Hello @palisadoes , I am interested in contributing to this Issue. Can you please confirm if this issue has been resolved or if there are any updates on its progress? If the issue is still open, I would like to work on it and submit a pull request. Thank you.

**Comment by iamrahulyele** [comment] 2023-04-02 13:09
Hello Peter,

Thank you for assigning the issue to me. And I really apologize for
reaching you this late, I was trying to login to the app using the steps,
but I failed. Please could you provide any testing login details or help me
create one. I'm not a backend person.

Thank you for your understanding.
Waiting for your reply.

Rahul Yele.

**Comment by palisadoes** [comment] 2023-04-03 04:42
Please ask the #talawa-mobile slack channel for assistance.

**Comment by iamrahulyele** [comment] 2023-04-03 10:12
Thank you for your response.

I'm afraid, I don't have access to slack. Can you provide that for me?

**Comment by iamrahulyele** [comment] 2023-04-03 11:24
Hey Peter,

I got the access.
Thank you for your help.

Have a great day ahead.

**Comment by tamojitalwaysghosh** [comment] 2023-04-18 05:06
is this issue still open? I can fix it...

**Comment by iamrahulyele** [comment] 2023-04-18 06:29
Yes, it's open. Some issue with the CropImage widget. Working on that.

**Comment by tamojitalwaysghosh** [comment] 2023-04-18 06:55
ok, wish you a good luck

**Comment by iamrahulyele** [comment] 2023-04-18 16:19
Hey @tamojitalwaysghosh if you can fix this, please take over.

**Comment by iamrahulyele** [comment] 2023-04-18 16:24
Hey @palisadoes please assign this issue to @tamojitalwaysghosh

**Comment by tamojitalwaysghosh** [comment] 2023-04-19 02:14
Thanks @iamrahulyele @palisadoes I will try to fix it as fast as possible.

**Comment by Saadkhanx** [comment] 2023-10-08 18:23
Hello @palisadoes if this issue is still open can you please assign it to me.

**Comment by palisadoes** [comment] 2023-10-13 03:47
@Ayush0Chaudhary Is this still an issue in the mobile app?

**Comment by Ayush0Chaudhary** [comment] 2023-10-13 05:18
> @Ayush0Chaudhary Is this still an issue in the mobile app?

No peter

**Closed** 2023-10-13 07:05 UTC
Labels: good first issue, feature request, points 01
