### ISSUE TITLE
Cannot create events in the mobile app because of Google notifications

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2195] opened 2023-12-01 22:48 UTC
**Describe the bug**
- Please work with @Ayush0Chaudhary for comments, advice and review of your PR.

Creating events fails with a `Notification Error` 

**To Reproduce**

1. Start app
2. Click on events
3. Add an event
4. Save event
5. Error is seen

**Expected behavior**
- There should be a no error

**Actual behavior**
- Error

**Screenshots**
-https://youtu.be/86AzK_Y_GCQ?t=429

**Additional details**
- We are no longer using the Firebase notifications feature and therefore this must be removed from the add event workflow. Non Firebase notifications is a GSoC 2024 draft idea
- You may need to coordinate your efforts with an API developer
- You must get the test **_code coverage up to 100%_** for any edited files. No functionality must be removed to achieve this goal

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Abhisheksainii** [comment] 2023-12-10 09:14
@noman2002 , I have found the cause of the issue, I will be needing an API developer from talawa-api to help me in resolving this issue as this issue.
Cause- when creating an event a notification is sent from the backend through this function ( admin.messaging().send() ). This needs to be removed or commented from the api code.

**Closed** 2024-01-07 22:56 UTC
Labels: bug, no-issue-activity
