### ISSUE TITLE
[Feature] Add functionality to crop the profile picture.

### ISSUE THREAD

**Issue by utkarshshendge** [PalisadoesFoundation/talawa#779] opened 2021-05-12 16:25 UTC
**Is your feature request related to a problem? Please describe.**
Currently, we have` image_picker` to pick the image, but we cannot crop it. We are picking up profile picture at two places, _signup screen_ and _update profile screen_. 

**Describe the solution you'd like**
There should be a feature to crop the profile picture similar to WhatsApp, Instagram.

**Additional context**
If you are interested to work on this  issue, please ask, mentors/maintainers to assign it.

**Comment by afaanshariff** [comment] 2021-05-13 08:25
@Sagar2366 @palisadoes I would like to work on this issue.

**Comment by afaanshariff** [comment] 2021-05-13 08:25
Am GitHub extern

**Comment by palisadoes** [comment] 2021-05-14 16:38
@afaanshariff Please put your ID in the comments

**Comment by afaanshariff** [comment] 2021-05-15 04:59
Can I know which id to submit here??

**Comment by palisadoes** [comment] 2021-05-15 05:47
You should have been assigned an ID when you created your account in the GitHub Externship portal. Please check.

**Comment by afaanshariff** [comment] 2021-05-15 09:56
There's an issue with my application number, as soon it's resolved I'll comment it down here.
Untill the issue is solved I'll be working on this issue.

**Comment by afaanshariff** [comment] 2021-05-16 14:47
Sir/Madam here's my application number - 16-05_AFF633_tfa_262 .

**Comment by afaanshariff** [comment] 2021-05-16 14:47
sorry for the delay.

**Comment by afaanshariff** [comment] 2021-05-17 06:45
I've added the functionality to crop the image, but while I was testing on different devices, there's an issue with taking pictures on the device. Image_picker package which is used to capture an image using the device has lots of issues within it. When I try to capture the image I lost connection with the device while I was running the app in debug mode and also the app froze. You can also refer to the link down below and also this issue was raised in 2019 and it's yet to be solved. The makers of the image_picker are waiting for the flutter team to resolve this issue.
Link to the issue - https://github.com/flutter/flutter/issues/48016

**Comment by afaanshariff** [comment] 2021-05-17 06:49
@Sagar2366 @palisadoes shall I raise an issue separately of the image_picker package or if it's not necessary shall I submit my PR in where I've added the crop feature functionality.

**Comment by afaanshariff** [comment] 2021-05-24 14:31
@utkarshshendge I request you to close this issue.

**Closed** 2021-05-24 14:59 UTC
Labels: github-externship
