### ISSUE TITLE
No Exit Pop on Home or Authorisation screen

### ISSUE THREAD

**Issue by ItsAdityaKSingh** [PalisadoesFoundation/talawa#1104] opened 2022-01-04 18:36 UTC
**Is your feature request related to a problem? Please describe.**
There is no emergency pop-up confirmation for exiting the home screen. Users may, by mistake, click the back button, and it would close the app.

**Describe the solution you'd like**
Instead, we could provide an emergency pop-up to confirm the exit of our users from the app.

**Comment by palisadoes** [comment] 2022-01-05 20:27
Please provide screen shots of what you are proposing to fix to help clarify the issue.

**Comment by ItsAdityaKSingh** [comment] 2022-01-06 14:50
<img src="https://i.ytimg.com/vi/Th0e_WO4Kks/maxresdefault.jpg" width="500"/>
This pop-up, whenever someone presses the back button when on the home screen or auth screen, a pop-up appears confirming whether the person really wants to exit or was by mistake and the person would want to continue.

**Comment by palisadoes** [comment] 2022-01-06 19:02
Can you please show where the issue is with a screen shot or video?

**Comment by ItsAdityaKSingh** [comment] 2022-01-07 10:24
Yeah sure. It's more of a feature that needs to be implemented in an app to avoid unwanted endings of sessions while using and is currently absent in talawa!

https://user-images.githubusercontent.com/69353350/148529779-4296e37b-3021-4d47-9890-0aafd5dde26d.mov


As you can see upon pressing back, the app closes immediately. Instead, it can give ask for a confirmation like this:

<p align="center">
 <img width="212" alt="Screenshot 2022-01-07 at 3 51 29 PM" src="https://user-images.githubusercontent.com/69353350/148530005-d0cb58ca-27f6-485c-9d2c-7a0d8d348278.png">
</p>

**Comment by palisadoes** [comment] 2022-01-08 04:06
Thanks, but this action isn't present in any of the major apps on my mobile device. Let's keep with the best practices of these developers. I'm going to close this issue.

**Closed by palisadoes** 2022-01-08 04:06 UTC
Labels: unapproved, feature request
