### ISSUE TITLE
The member page stuck if not joined into any organization.(Bug)

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa#429] opened 2021-03-20 18:34 UTC
Issue Description: The member page stucks if not joined into any organization.
Issue Severity: medium
Environment Details: Issue found mostly in the talawa\lib\views\pages\organization\members
Observed Behaviour: The member page stucks if not joined into any organization.
Expected Behaviour: clicking yes should allow us to join the organization.
Does this issue need immediate attention?  yes
Are you willing to work on this issue: Yes, I am willing to work on this issue. Please assign this to me!
![Capture](https://user-images.githubusercontent.com/55004621/111881933-ddad5e80-89d8-11eb-933c-6dbc6c4f5a86.JPG)
.dart

**Comment by CyberWake** [comment] 2021-03-21 03:03
Would like to work on this one currently i have fixed all the issues coming in profile page due to any of the organization related issue. I would we very happy to resolve this one which could help me enable some state management and code refactoring in correspondence to the whole organization module. @yasharth291 hope you won't mind if I work on this one with some state management from the module. @Sagar2366 @heyjordn can you please assign this one to me. And please review #424 this merge is going to be of much use. 😊

**Comment by CyberWake** [comment] 2021-03-21 03:10
basically the expected behavior isn't achieved due to:
1. the organization could be private which leads the user to wait for admins approval.
2. There could have been some internet issue which cause the user to add the corresponding data to the database but couldn't save the organization details in the preferences for future retrieval. In this scenario the profile page shows user hasn't joined any organization, but he can see the switch organization tile from where he can switch and see his joined organization.

This issue wasn't resolved in #424 as it was pertaining to organization settings only. would be glad to contribute more towards the module.

**Comment by Sagar2366** [comment] 2021-03-21 03:43
@CyberWake let @yasharth291 work on this, he will also get exposure to profile module.
@yasharth291 if you don't want to work on this let me know.

**Comment by yasharth291** [comment] 2021-03-21 06:32
i totally want to work on it

**Comment by CyberWake** [comment] 2021-03-21 07:10
> i totally want to work on it

sure go ahead. It's your call.😊

**Comment by yasharth291** [comment] 2021-03-21 11:50
@Sagar2366 this bug is solved sir can i be assigned any other bug please.

**Closed** 2021-03-23 18:59 UTC
Labels: bug, good first issue
