### ISSUE TITLE
Code requires formatting, for readability.

### ISSUE THREAD

**Issue by kartik-pant-23** [PalisadoesFoundation/talawa#127] opened 2021-03-12 08:06 UTC
**Description**
A code that is well formatted with proper indentation in accordance with conventional guidelines, is more readable. Going through the code, I found it as an enhancement, for all of us out there.

**Am I doing this?**
I have formatted the code and will be making a pull request for the same.

**Comment by yasharth291** [comment] 2021-03-12 08:10
#103  please close this issue as it is duplicate of #103

**Comment by yasharth291** [comment] 2021-03-12 08:10
@kartik-pant-23

**Comment by yasharth291** [comment] 2021-03-12 08:11
and you should close your pr as well because it has merge conflicts.

**Comment by kartik-pant-23** [comment] 2021-03-12 08:13
I have formatted the code and probably i was on different branch while working, which seems to bring those conflicts. Adding comments and refactoring the indentations, doesn't seem similar though.

**Comment by yasharth291** [comment] 2021-03-12 08:14
it is same as making code easy to understand. It is duplicate of #103

**Comment by kartik-pant-23** [comment] 2021-03-12 08:17
Are you one of the maintainers? Can you guide me how to go about the missing files in master branch. I was on a different branch while making the pull request, which caused conflicts.

**Comment by yasharth291** [comment] 2021-03-12 08:21
please read the issues before i am mentioning the issue about it #92

**Comment by kartik-pant-23** [comment] 2021-03-12 08:26
Thank you.

**Comment by yasharth291** [comment] 2021-03-12 08:27
now you can close this issue as it is duplicate and you can delete the pr as well. You have to wait till #92  is closed

**Comment by EmperorYP7** [comment] 2021-03-12 08:37
@yasharth291 Chill out! 😆

**Comment by yasharth291** [comment] 2021-03-12 08:37
@EmperorYP7  it is creating spam issues 👍🏻

**Comment by kartik-pant-23** [comment] 2021-03-12 08:38
PR has been closed, because it was having issues with the current codebase

**Comment by yasharth291** [comment] 2021-03-12 08:39
ok thanks for cooperation

**Comment by kartik-pant-23** [comment] 2021-03-12 08:39
Thanks to you for helping like a maintainer.

**Comment by yasharth291** [comment] 2021-03-12 08:41
no problem but i am not maintainer xD

**Comment by kartik-pant-23** [comment] 2021-03-12 09:11
Glad you understood, can totally understand this enthusiasm.

**Comment by DeltaHarbinger** [comment] 2021-03-14 01:53
Hey @kartik-pant-23, we recently merged #151 which includes a number of fixes on the master branch. Everyone seems to be able to build now. I agree with your analysis that a lot of the code isn't formatted properly, so feel free to pull the major changes on master and make a pull request with any changes related to this issue.

**Comment by Sagar2366** [comment] 2021-03-16 18:22
Closing this issue as duplicate of https://github.com/PalisadoesFoundation/talawa/issues/103

**Closed by Sagar2366** 2021-03-16 18:22 UTC
Labels: PR-Unapproved, discussion, duplicate, enhancement
