### ISSUE TITLE
[Bug]: Missing Tab Bar on first Signup

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa#193] opened 2021-03-14 04:33 UTC
### Description
After user Signup, the user is taken to the Profile Screen. The entire screen is missing `Bottom Navigation Bar` due to which user cannot see posts and other navigation screen.
 
### Observed Behaviour 
Navigation Bar is not shown
![WhatsApp Image 2021-03-14 at 9 59 26 AM](https://user-images.githubusercontent.com/35868598/111057307-70676e00-84ac-11eb-99fd-7a68f9d0db74.jpeg)

### Expected Behaviour
Bottom Navigation Bar should appear at the Bottom of the screen

I am working on this issue.

**Comment by yasharth291** [comment] 2021-03-14 04:34
it is because there is no feed for you the issues title should be changed i guess

**Comment by sumitra19jha** [comment] 2021-03-14 05:14
No. It's not there because the main function uses userID to decide its navigation to Home Screen or Login Screen. After signup, user is navigated to join organisation page then ===> Feed Page. There is no notifier used to alert to load the HomeScreen Present in the main function.

**Comment by CyberWake** [comment] 2021-03-14 20:32
Resolved this issue and made a PR #289. Kindly look into this one and if possible please review it.😃

**Comment by sumitra19jha** [comment] 2021-03-15 05:13
I added a comment

**Comment by Sagar2366** [comment] 2021-03-15 17:49
Closing this issue as it is duplicate of https://github.com/PalisadoesFoundation/talawa/issues/288

**Closed by Sagar2366** 2021-03-15 17:49 UTC
Labels: duplicate
