### ISSUE TITLE
Overflow issue when entering the events page

### ISSUE THREAD

**Issue by DMills27** [PalisadoesFoundation/talawa#1582] opened 2023-02-27 11:18 UTC
**Describe the bug**

**To Reproduce**

[![Follow the steps outlined here till 1:18](https://img.youtube.com/vi/ix3eSReJj2k?/0.jpg)](https://www.youtube.com/watch?v=ix3eSReJj2k?t=54)

**Expected behavior**
The overflow issue in the top right-hand corner should not be present.

**Screenshots**

<img width="325" alt="Screenshot at Feb 27 06-11-06" src="https://user-images.githubusercontent.com/5251658/221549101-0115e9b6-104c-4b1d-b74a-69e146191230.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment] 2023-02-27 21:51
Closing duplicate of:
- https://github.com/PalisadoesFoundation/talawa/issues/1561

**Comment by palisadoes** [comment] 2023-02-27 21:51
Closing. Duplicate of:
- https://github.com/PalisadoesFoundation/talawa/issues/1561

**Closed by palisadoes** 2023-02-27 21:51 UTC
Labels: bug
