### ISSUE TITLE
Bug: Post comments are invisible in Individual Post Page.

### ISSUE THREAD

**Issue by Azad99-9** [PalisadoesFoundation/talawa#2333] opened 2024-01-18 18:59 UTC
**Describe the bug**
`Post comments` in `individual post page` are empty and `invisible` despite the `existence` of comments.

**To Reproduce**

1. Login and Join an organisation.
2. Create a post in case of empty posts.
3. Find the created post in news feed and click on its comment option.
4. Add a new comment.
5. Navigate back to news feed.
6. Once again click on same post comment option.

**Expected behavior**
The previously created comment should be visible.

**Actual behavior**
The comment list is empty despite the comment icon showing non zero value.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa/assets/120930148/981d45d6-854d-4823-9028-f3d2a058ff81

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by imshivam-gupta** [comment] 2024-01-19 14:24
@noman2002 Can you please assign this to me

**Comment by imshivam-gupta** [comment] 2024-01-21 17:08
I have found the cause of bug and will create a PR to fix this till tomorrow.

**Closed** 2024-02-03 19:46 UTC
Labels: bug, feature request
