### ISSUE TITLE
Upgrade the project to Android Embedding v2

### ISSUE THREAD

**Issue by SriramPatibanda** [PalisadoesFoundation/talawa#129] opened 2021-03-12 10:48 UTC
The current app uses an older version of Android Embedding which will be deprecated soon. The app needs to be migrated to Android embedding v2 in order to use the new Android plugin development APIs.

**Comment by SriramPatibanda** [comment] 2021-03-12 10:49
I'm willing to work on this issue. Kindly assign it to me @palisadoes .

**Comment by yasharth291** [comment] 2021-03-12 10:52
sorry to say but maintainers are already working on it.
so this issue is duplicate of this #111. Please close this issue to create spam issues. @SriramPatibanda

**Comment by yasharth291** [comment] 2021-03-12 10:53
you can mention you ideas in #111

**Comment by SriramPatibanda** [comment] 2021-03-12 10:58
> sorry to say but maintainers are already working on it.
> so this issue is duplicate of this #111. Please close this issue to create spam issues. @SriramPatibanda

Hey there! Thank you for letting me know this. Does the organization have an IRC or Slack where discussions happen?

**Comment by yasharth291** [comment] 2021-03-12 11:00
yeah you should mail the maintainer and they will send it.

**Comment by yasharth291** [comment] 2021-03-12 11:00
now if the doubt is clear you can close this issue☺️☺️

**Comment by SriramPatibanda** [comment] 2021-03-12 11:01
The issue is a duplicate of #111 . Hence it is closed.

**Closed** 2021-03-12 11:01 UTC
