### ISSUE TITLE
Pre-commits for minor commands.

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa#2038] opened 2023-10-01 08:27 UTC
**Is your feature request related to a problem? Please describe.**
Pre-commit for running formatting and other minor commands, could be useful and will make our CI/CD faster

**Describe the solution you'd like**
git hooks

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359
yes

**Comment by Ayush0Chaudhary** [comment] 2023-10-01 08:27
@palisadoes can we add this?

**Comment by literalEval** [comment] 2023-10-02 18:08
@Ayush0Chaudhary @palisadoes duplicate of #1766

**Closed** 2023-10-02 18:09 UTC
Labels: feature request
