### ISSUE TITLE
Get Test Code Coverage to 35%

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#986] opened 2021-09-25 17:12 UTC
**Describe the bug**
We need to improve the reliability of our code. The test code coverage is only 30% currently. We need to raise this to 35%

**Before Running**

You will need to install the `lcov` package to get the `genthml` executable. For Ubuntu Linux the command would be:

```
$ sudo apt-get install lcov
$ which genhtml
/usr/bin/genhtml
$
```
The `which` command shows the location of the `genthml` executable.

**To Reproduce**

Run the commands below:
```
cd talawa
flutter pub get
flutter test --coverage
genhtml coverage/lcov.info -o coverage
```
You will get a final output from the `genhtml` command looking like this:

```
Processing file lib/widgets/add_members_bottom_sheet.dart
Processing file lib/widgets/rich_text.dart
Processing file lib/widgets/event_admin_fab.dart
Writing directory view page.
Overall coverage rate:
  lines......: 30.3% (1805 of 5949 lines)
  functions..: no data found
```

In this example the coverage is only 30.3% We need to get it to 35% by adding more code tests

**Comment by bayush-9** [comment] 2021-09-26 15:46
@palisadoes I am not able to reproduce the coverage data after inputting "genhtml coverage/lcov.info -o coverage" in terminal. It says "The term 'genhtml' is not recognized as the name of a cmdlet, function, script file, or operable program." Can you help me out ?

**Comment by palisadoes** [comment] 2021-09-26 17:07
@bayush-9 You will need to install lcov. For linux the command would be:

```
$ sudo apt-get install lcov
$ which genhtml
/usr/bin/genhtml
$
```
The `which` command shows the location of the `genthml` executable.

**Comment by Hasan1605** [comment] 2021-10-20 08:16
Thanks for the reply and can you share the details if I can help you in
this.
Regards

**Comment by Literal-Eval** [comment] 2021-12-26 09:05
Is this worked upon ? If not, kindly assign this to me.

**Comment by palisadoes** [comment] 2021-12-26 12:57
@Ashish-AI I've reassigned this issue as it's been dormant for some time.

**Comment by Literal-Eval** [comment] 2021-12-26 13:25
A little help I need. 

- Should tests be written for custom widgets in widgets directory ?
- If so, then what should the tests be about ? Just testing widget with dummy data and checking it's text etc ?

**Comment by palisadoes** [comment] 2021-12-26 14:21
@Literal-Eval 
- The widget tests have their [own directory](https://github.com/PalisadoesFoundation/talawa/tree/develop/test/widget_tests).
- The tests should use dummy data to ensure that the functionality is OK, just as you mentioned.

**Comment by Literal-Eval** [comment] 2022-01-10 14:27
Fixed

**Comment by Literal-Eval** [comment] 2022-01-10 14:27
Please close this issue now.

**Closed** 2022-01-10 16:37 UTC
Labels: bug, good first issue, test
